services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./.env:/.env  # Montar o arquivo .env no container
    working_dir: /app
    command: ["./main"]
    env_file:
      - .env  # Usar o arquivo .env para as variáveis de ambiente

  db:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
